AllCops:
  DisabledByDefault: true
  Exclude:
    - db/**/*
    - script/**/*
    - config/**/*

Metrics/LineLength:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#max-line-length
  Max: 120

Style/TrailingWhitespace:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#no-trailing-whitespace
  Enabled: true

Style/TrailingBlankLines:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#end-file-newline
  EnforcedStyle: final_newline

Style/SpaceAroundOperators:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true
  MultiSpaceAllowedForOperators:
    - '='
    - '=>'

Style/SpaceAfterComma:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true

Style/SpaceAfterColon:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true

Style/SpaceAfterSemicolon:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true

