AllCops:
  DisabledByDefault: true
  Exclude:
    - db/**/*
    - script/**/*
    - config/**/*

Style/IndentationConsistency:
  Enabled: true
  AutoCorrect: true

Style/CommentIndentation:
  Enabled: true
  AutoCorrect: true

## Coding Style

Style/Tab:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#tabs
  Enabled: true

Style/IndentationWidth:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#tabs
  Enabled: true

Metrics/LineLength:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#max-line-length
  Max: 120

Style/TrailingWhitespace:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#no-trailing-whitespace
  Enabled: true

Style/TrailingBlankLines:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#end-file-newline
  EnforcedStyle: final_newline

Style/SpaceAroundOperators:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true
  MultiSpaceAllowedForOperators:
    - '='
    - '=>'

Style/SpaceAroundEqualsInParameterDefault:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  EnforcedStyle: space

Style/SpaceAfterComma:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true

Style/SpaceAfterColon:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true

Style/SpaceAfterSemicolon:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true

Style/SpaceBeforeBlockBraces:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true
  EnforcedStyle: space

Style/SpaceInsideBlockBraces:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true
  EnforcedStyle: space
  # Valid values are: space, no_space
  EnforcedStyleForEmptyBraces: no_space
  # Space between { and |. Overrides EnforcedStyle if there is a conflict.
  SpaceBeforeBlockParameters: true

Style/SpaceInsideHashLiteralBraces:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Style/SpaceInsideStringInterpolation:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#spaces-around-operators
  Enabled: true
  EnforcedStyle: no_space

Style/SpaceInsideParens:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#no-spaces-around-delimiters
  Enabled: true

Style/SpaceInsideBrackets:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#no-spaces-around-delimiters
  Enabled: true

Style/CaseIndentation:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#case-indentation
  Enabled: true

Style/ElseAlignment:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#case-indentation
  Enabled: true

Style/RescueEnsureAlignment:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#case-indentation
  Enabled: true

Lint/EndAlignment: 
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#case-indentation
  Enabled: true
  AutoCorrect: true

Style/SpaceAfterNot:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#no-space-after-not
  Enabled: true

Style/EmptyLineBetweenDefs:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#lines-between-defs
  Enabled: true
  AllowAdjacentOneLineDefs: false

## Syntax

Style/MethodDefParentheses:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#method-parentheses
  Enabled: true

Style/DefWithParentheses:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#method-parentheses
  Enabled: true

Style/AndOr:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#no-and-or-keyword
  Enabled: true

Style/SpaceAfterMethodName:
  StyleGuide: https://github.com/backupify/backupify_styleguides/blob/master/RubyStyleguide.md#no-space-after-method-name
  Enabled: true
